#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
pushd "$DIR/.." > /dev/null

echo
echo -n "Enter page name and press [ENTER]: "
read name

if [ -n "$name" ]; then
	mkdir -p "pages/$name"
	cp Copyable/index.md "pages/$name/index.md"
	sed -i -e "s/Index/$name/g" "pages/$name/index.md"
	rm "pages/$name/index.md-e" 2> /dev/null
	echo
	echo "Made page: $name"
	echo "Edit it in the pages folder."
else
	echo
	echo "Didn't make a page."
fi

echo -n "Press [ENTER] to continue..."
read nothing

popd > /dev/null
